title: Mustafa AŞKIN # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Researcher
  <br><br>
  TurkStat
  <br><br>
  <a href="https://www.linkedin.com/in/mustafa-a%C5%9Fkin-13258a46/">View My LinkedIn Profile</a> 
  
  <br><br>
  
  <a href="https://medium.com/@mustafaaskin1981">View My Medium Profile</a> 
  

  
theme: jekyll-theme-minimal
google_analytics: G-V5R29R018P # your Google Analytics tracking ID here
